Update library to reflect styleguide
- Major upgrade and rewrite of all scripts
- Update all scripts to use function, local variables and call function
  within
- Update all scripts that require a usage guide to set as local variable
- Update all scripts with dependency check
- Update all scripts with help and invalid option test flags
- Delete all scripts that are OS X dependent and Git dependent, as
  they'll be moved to a separate repository
- Create man pages for any necessary script
- Create more functions, `fs`, `get-cert-names`, `json`, `rgb-to-xterm`,
  `targz`, `update-ctags`.

Issue: #6

diff --git a/bin/cdls b/bin/cdls
--- a/bin/cdls
+++ b/bin/cdls
@@ -6,37 +6,40 @@
 # Description:
 #   Change into directory, list all files
 #
-# Dependencies:
-#   None
-#
-# Configuration:
-#   @param   dir    optional
-#
 # Usage:
 #   `cdls ~/Downloads`
 
-usage="$(basename $0): usage: $(basename $0) [-r] [dir]"
+_cdls() {
+	local usage="$(basename $0): usage: $(basename $0) [[-h|--help] [-r|--reverse]] [dir]"
+	local ORDER opt
 
-# Test for known flags
-for opt in $@
-do
-	case $opt in
-		-r)
-			ORDER="-r"
-			;;
-		# test for an invalid flag, exit if not a valid flag
-		-*|--*)
-			printf "bash: %s: %s: Invalid option\n%s\n" "$(basename "$0")" "$opt" "${usage}"
-			exit 1
-			;;
-	esac
-done
+	# Test for known flags
+	for opt in $@
+	do
+		case $opt in
+			-h|--help)
+				printf "%s\n" "${usage}"
+				exit
+				;;
+			-r|--reverse)
+				ORDER="-r"
+				;;
+			# test for an invalid flag, exit if not a valid flag
+			-*|--*)
+				printf "%s: usage: %s: invalid option\n%s\n" "$(basename "$0")" "$opt" "${usage}"
+				exit 1
+				;;
+		esac
+	done
 
-# if operand is not a directory, and not empty
-if [[ -d "$1" ]]; then
-	cd $1
-else
-	cd .
-fi
+	# if operand is not a directory, and not empty
+	if [[ -d "$1" ]]; then
+		cd $1
+	else
+		cd ${PWD}
+	fi
 
-ls ${ORDER}
+	ls -lAFGHhOoT ${ORDER}
+}
+
+_cdls "$@"
diff --git a/bin/cleanup b/bin/cleanup
--- a/bin/cleanup
+++ b/bin/cleanup
@@ -15,9 +15,38 @@
 # Usage:
 #   `cleanup filename.txt`
 
-# (find .) Find within the current directory
-# (-type f) match anything with the type of regular file
-# (-name "${1}") last component of the pathname matches argument
-# (-ls) printout the standard output of matched files
-# (-delete) delete the matched files
-find . -type f -name "${1}" -ls -delete
+_cleanup() {
+	local usage="$(basename $0): usage: $(basename $0) [-h|--help] $(tput smul)pattern$(tput rmul)"
+	local opt
+	local pattern="$1"
+
+	# Test for known flags
+	for opt in $@
+	do
+		case $opt in
+			-h|--help)
+				printf "%s\n" "${usage}"
+				exit
+				;;
+			# test for an invalid flag, exit if not a valid flag
+			-*|--*)
+				printf "%s: usage: %s: invalid option\n%s\n" "$(basename "$0")" "$opt" "${usage}"
+				exit 1
+				;;
+		esac
+	done
+
+	if [[ ! "${pattern}" ]]; then 
+		printf "bash: %s: No pattern specified\n" "$(basename "$0")"
+		exit 1; 
+	fi
+
+	# (find .) Find within the current directory
+	# (-type f) match anything with the type of regular file
+	# (-name "${1}") last component of the pathname matches argument
+	# (-ls) printout the standard output of matched files
+	# (-delete) delete the matched files
+	find . -type f -name "${pattern}" -ls -delete
+}
+
+_cleanup "$@"
diff --git a/bin/favicon b/bin/favicon
--- a/bin/favicon
+++ b/bin/favicon
@@ -25,51 +25,69 @@
 #
 # Concept from http://bergamini.org/computers/creating-favicon.ico-icon-files-with-imagemagick-convert.html
 
-CONVERT_CMD=`which convert`
-SRC_IMAGE=$1
-PWD=`pwd`
+_favicon() {
+	local usage="$(basename $0): usage: $(basename $0) [-h|--help] $(tput smul)file$(tput rmul)"
+	local CONVERT_CMD=$(which convert)
+	local SRC_IMAGE="$1"
+	local opt
 
-if [ -z $CONVERT_CMD ] || [ ! -f $CONVERT_CMD ] || [ ! -x $CONVERT_CMD ];
-then
-    echo "ImageMagick needs to be installed to run this script"
-    exit;
-fi
+	# Test for known flags
+	for opt in $@
+	do
+		case $opt in
+			-h|--help)
+				printf "%s\n" "${usage}"
+				exit
+				;;
+			# test for an invalid flag, exit if not a valid flag
+			-*|--*)
+				printf "%s: usage: %s: invalid option\n%s\n" "$(basename "$0")" "$opt" "${usage}"
+				exit 1
+				;;
+		esac
+	done
 
-if [ -z $SRC_IMAGE ];
-then
-	echo "You must supply a source image as the argument to this command."
-	exit;
-fi
+	if [ -z $CONVERT_CMD ] || [ ! -f $CONVERT_CMD ] || [ ! -x $CONVERT_CMD ]; then
+		printf "%s⊘ Error:%s ImageMagick needs to be installed to run this script. Aborting\n" "$(tput setaf 1)" "$(tput sgr0)" "$@"
+		exit;
+	fi
 
-if [ ! -f $SRC_IMAGE ];
-then
-    echo "Source image \"$SRC_IMAGE\" does not exist."
-    exit;
-fi
+	if [ -z $SRC_IMAGE ]; then
+		printf "%s: usage: no file specified\n%s\n" "$(basename "$0")" "${usage}"
+		exit 1
+	fi
 
-echo "Generating square base image"
-$CONVERT_CMD $SRC_IMAGE -resize 256x256! -transparent white $PWD/favicon-256.png
+	if [ ! -f $SRC_IMAGE ]; then
+		printf 'bash: %s: No such file\n' "${SRC_IMAGE}"
+		exit;
+	fi
 
-echo "Generating various sizes for ico"
-$CONVERT_CMD $PWD/favicon-256.png -resize 16x16 $PWD/favicon-16.png
-$CONVERT_CMD $PWD/favicon-256.png -resize 32x32 $PWD/favicon-32.png
-$CONVERT_CMD $PWD/favicon-256.png -resize 64x64 $PWD/favicon-64.png
-$CONVERT_CMD $PWD/favicon-256.png -resize 128x128 $PWD/favicon-128.png
+	printf "Generating square base image\n"
+	$CONVERT_CMD $SRC_IMAGE -resize 256x256! -transparent white $PWD/favicon-256.png
 
-echo "Generating ico"
-$CONVERT_CMD $PWD/favicon-16.png $PWD/favicon-32.png $PWD/favicon-64.png $PWD/favicon-128.png $PWD/favicon-256.png -colors 256 $PWD/favicon.ico
+	printf "Generating various sizes for ico\n"
+	$CONVERT_CMD $PWD/favicon-256.png -resize 16x16 $PWD/favicon-16.png
+	$CONVERT_CMD $PWD/favicon-256.png -resize 32x32 $PWD/favicon-32.png
+	$CONVERT_CMD $PWD/favicon-256.png -resize 64x64 $PWD/favicon-64.png
+	$CONVERT_CMD $PWD/favicon-256.png -resize 128x128 $PWD/favicon-128.png
 
-echo "Generating touch icons"
-$CONVERT_CMD $PWD/favicon-256.png -resize 57x57 $PWD/apple-touch-icon.png
-cp $PWD/apple-touch-icon.png $PWD/apple-touch-icon-precomposed.png
-cp $PWD/apple-touch-icon.png $PWD/apple-touch-icon-57x57-precomposed.png
-$CONVERT_CMD $PWD/favicon-256.png -resize 72x72 $PWD/apple-touch-icon-72x72-precomposed.png
-$CONVERT_CMD $PWD/favicon-256.png -resize 114x114 $PWD/apple-touch-icon-114x114-precomposed.png
-$CONVERT_CMD $PWD/favicon-256.png -resize 144x144 $PWD/apple-touch-icon-144x144-precomposed.png
+	printf "Generating ico\n"
+	$CONVERT_CMD $PWD/favicon-16.png $PWD/favicon-32.png $PWD/favicon-64.png $PWD/favicon-128.png $PWD/favicon-256.png -colors 256 $PWD/favicon.ico
 
-echo "Removing temp files"
-rm -rf $PWD/favicon-16.png
-rm -rf $PWD/favicon-32.png
-rm -rf $PWD/favicon-64.png
-rm -rf $PWD/favicon-128.png
-rm -rf $PWD/favicon-256.png
+	printf "Generating touch icons\n"
+	$CONVERT_CMD $PWD/favicon-256.png -resize 57x57 $PWD/apple-touch-icon.png
+	cp $PWD/apple-touch-icon.png $PWD/apple-touch-icon-precomposed.png
+	cp $PWD/apple-touch-icon.png $PWD/apple-touch-icon-57x57-precomposed.png
+	$CONVERT_CMD $PWD/favicon-256.png -resize 72x72 $PWD/apple-touch-icon-72x72-precomposed.png
+	$CONVERT_CMD $PWD/favicon-256.png -resize 114x114 $PWD/apple-touch-icon-114x114-precomposed.png
+	$CONVERT_CMD $PWD/favicon-256.png -resize 144x144 $PWD/apple-touch-icon-144x144-precomposed.png
+
+	printf "Removing temp files\n"
+	rm -rf $PWD/favicon-16.png
+	rm -rf $PWD/favicon-32.png
+	rm -rf $PWD/favicon-64.png
+	rm -rf $PWD/favicon-128.png
+	rm -rf $PWD/favicon-256.png
+}
+
+_favicon "$@"
diff --git a/bin/ie-vm b/bin/ie-vm
--- a/bin/ie-vm
+++ b/bin/ie-vm
@@ -16,32 +16,60 @@
 # Usage:
 #   `ie-vm 8`
 
-ie-vm() {
-	local usage="$(basename "$0"): usage: $(basename "$0") [8|9|10|11]"
-	local baseUrl="https://az412801.vo.msecnd.net/vhd/IEKitV1_Final/VirtualBox/OSX/"
+_ie-vm() {
+	local usage="$(basename "$0"): usage: $(basename "$0") [8|9|10|11] $(tput smul)dir$(tput rmul)"
+	local opt
+	local index="$1"
+	local directory="$2"
+	local baseUrl="https://www.modern.ie/vmdownload?platform=mac&virtPlatform=virtualbox&browserOS="
 	declare -A versions=( 
 		# IE8 XP
-		["8"]="IE8_XP/IE8.XP.For.MacVirtualBox.ova"
+		[8]="IE8-WinXP&parts=2&filename=VMBuild_20131127/VirtualBox/IE8_WinXP/Mac/IE8.WinXP.For.MacVirtualBox.part{1.sfx,2.rar}"
 		# IE9 Win7
-		["9"]="IE9_Win7/IE9.Win7.For.MacVirtualBox.part{1.sfx,2.rar,3.rar,4.rar,5.rar}"
+		[9]="IE9-Win7&parts=4&filename=VMBuild_20131127/VirtualBox/IE9_Win7/Mac/IE9.Win7.For.MacVirtualBox.part{1.sfx,2.rar,3.rar,4.rar}"
 		# IE10 Win8
-		["10"]="IE10_Win8/IE10.Win8.For.MacVirtualBox.part{1.sfx,2.rar,3.rar}"
+		[10]="IE10-Win8.1&parts=5&filename=VMBuild_20131127/VirtualBox/IE10_Win8/Mac/IE10.Win8.For.MacVirtualBox.part{1.sfx,2.rar,3.rar,4.rar,5.rar}"
 		# IE11 Win8.1
-		["11"]="IE11_Win8.1/IE11.Win8.1.For.MacVirtualBox.part{1.sfx,2.rar,3.rar}"
+		[11]="IE11-Win8.1&parts=4&filename=VMBuild_20140402/VirtualBox/IE11_Win8.1/Mac/IE11.Win8.1.For.MacVirtualBox.part{1.sfx,2.rar,3.rar,4.rar}"
 	)
+	local path="${versions[${index}]}"
+	local url="${baseUrl}${path}"
 
 	# Test for known flags
 	for opt in $@
 	do
 		case $opt in
+			-h|--help)
+				printf "%s\n" "${usage}"
+				exit
+				;;
 			# test for an invalid flag, exit if not a valid flag
 			-*|--*)
-				printf '%sbash: %s: %s: Invalid option\n' "-" "$(basename "$0")" "$opt" >&2
-				printf '%s\n' "$usage"
+				printf "%s: usage: %s: invalid option\n%s\n" "$(basename "$0")" "$opt" "${usage}"
 				exit 1
 				;;
 		esac
 	done
 
-	curl -O "$baseUrl/$version[$1]"
+	if [[ ! "${index}" ]]; then 
+		printf "bash: %s: No version specified\n" "$(basename "$0")"
+		exit 1; 
+	fi
+
+	[ ! ${versions[${index}]+abc} ] && printf "%s: usage: invalid version\n" "$(basename "$0")" && exit 1
+
+	if [[ ! "${directory}" ]]; then 
+		printf "bash: %s: No directory specified\n" "$(basename "$0")"
+		exit 1; 
+	fi
+
+	if [[ ! -d "${directory}" ]]; then 
+		printf "bash: %s: No such directory\n" "$(basename "$0")"
+		exit 1; 
+	fi
+
+	curl -O -L "${url}"
+	find . -type f -name "IE${index}*" -print | ( read file; mv "$file" "${directory}/$file" )
 }
+
+_ie-vm "$@"
diff --git a/bin/lint b/bin/lint
--- a/bin/lint
+++ b/bin/lint
@@ -19,13 +19,53 @@
 #   `lint html app/index.html`
 #   `lint js app/scripts.js`
 
-if [[ $1 == "html" ]]; then
-	htmlinspector "$2"
-elif [[ $1 == "css" ]]; then
-	csslint "$2"
-elif [[ $1 == "js" ]]; then
-	jslint "$2"
-else 
-	printf 'bash: %s: %s: Invalid option\n' "$(basename "$0")" "$1"
-	printf "%s: usage: %s [[-c|--css]| [-h|--html]| [-j|--javascript]] %sfile%s\n" "$(basename $0)" "$(basename $0)" "$(tput smul)" "$(tput rmul)"
-fi
+_lint() {
+	local usage="$(basename "$0"): usage: $(basename "$0") [[-c|--css]| [-h|--html]| [-j|--javascript]] $(tput smul)file$(tput rmul)"
+
+	# Test for known flags
+	for opt in $@
+	do
+		case $opt in
+			-h|--help)
+				printf "%s\n" "${usage}"
+				exit
+				;;
+			# test for an invalid flag, exit if not a valid flag
+			-*|--*)
+				printf "%s: usage: %s: invalid option\n%s\n" "$(basename "$0")" "$opt" "${usage}"
+				exit 1
+				;;
+		esac
+	done
+
+	if [[ $1 == "html" ]]; then
+		if ! type -P 'htmlinspector' &> /dev/null; then
+			printf "%s⊘ Error:%s htmlinspector is required to run %s\n" "$(tput setaf 1)" "$(tput sgr0)" "$(basename $0)"
+			printf "Aborting!\n"
+			exit
+		else
+			htmlinspector "$2"
+		fi
+	elif [[ $1 == "css" ]]; then
+		if ! type -P 'csslint' &> /dev/null; then
+			printf "%s⊘ Error:%s csslint is required to run %s\n" "$(tput setaf 1)" "$(tput sgr0)" "$(basename $0)"
+			printf "Aborting!\n"
+			exit
+		else
+			csslint "$2"
+		fi
+	elif [[ $1 == "js" ]]; then
+		if ! type -P 'jslint' &> /dev/null; then
+			printf "%s⊘ Error:%s jslint is required to run %s\n" "$(tput setaf 1)" "$(tput sgr0)" "$(basename $0)"
+			printf "Aborting!\n"
+			exit
+		else
+			jslint "$2"
+		fi
+	else 
+		printf '%s: usage: %s: invalid option\n%s\n' "$(basename "$0")" "$1" "${usage}"
+		exit 2
+	fi
+}
+
+_lint "$@"
diff --git a/bin/makefile b/bin/makefile
--- a/bin/makefile
+++ b/bin/makefile
@@ -10,11 +10,33 @@
 # Configuration:
 #   @param    file    required
 #
-# Usage: 
+# Usage:
 #   `create-makefile conf/settings.json`
 
-if [[ -f "$2" ]]; then
+_create-makefile() {
+	local usage="$(basename $0): usage: $(basename $0) [-h|--help] $(tput smul)pattern$(tput rmul)"
+	local opt
 
+	# Test for known flags
+	for opt in $@
+	do
+		case $opt in
+			-h|--help)
+				printf "%s\n" "${usage}"
+				exit
+				;;
+			# test for an invalid flag, exit if not a valid flag
+			-*|--*)
+				printf "%s: usage: %s: invalid option\n%s\n" "$(basename "$0")" "$opt" "${usage}"
+				exit 1
+				;;
+		esac
+	done
+
+	if ! test -f "$1" &>/dev/null; then
+		printf "bash: %s: No file specified\n" "$(basename "$0")"
+		exit 1
+	else
 cat <<EOF>> Makefile
 .PHONY: _pwd_prompt decrypt_conf encrypt_conf
 
@@ -31,9 +53,7 @@ decrypt_conf: _pwd_prompt
 encrypt_conf: _pwd_prompt
 	openssl cast5-cbc -e -in $1 -out $1.cast5
 EOF
+	fi
+}
 
-	printf "%s✓ Success:%s Makefile has been created.\n" "$(tput setaf 2)" "$(tput sgr0)"
-else
-	printf "%s⊘ Error:%s You didn't pass in a file. Aborting!\n" "$(tput setaf 1)" "$(tput sgr0)"
-	exit 1
-fi
+_create-makefile "$@"
diff --git a/bin/pid b/bin/pid
--- a/bin/pid
+++ b/bin/pid
@@ -13,21 +13,37 @@
 # Usage:
 #   `pid [processname]`
 
-usage="$(basename "$0"): usage: $(basename "$0") [processname [processname ...]]"
+_pid() {
+	local usage="$(basename "$0"): usage: $(basename "$0") [processname [processname ...]]"
+	local args arg opt
 
-if [[ "$1" == "-h" || "$1" == "--help" ]]; then
-	printf '%s\n' "$usage"
-	exit
-fi
-
-if [ ! "$1" ]; then
-	ps axo pid,tty,user,command
-else
-	args="$1"
-	shift 
-	for arg in "$@";
-	do 
-		args="${args}|${arg}"; 
+	# Test for known flags
+	for opt in $@
+	do
+		case $opt in
+			-h|--help)
+				printf "%s\n" "${usage}"
+				exit
+				;;
+			# test for an invalid flag, exit if not a valid flag
+			-*|--*)
+				printf "%s: usage: %s: invalid option\n%s\n" "$(basename "$0")" "$opt" "${usage}"
+				exit 1
+				;;
+		esac
 	done
-	echo $(ps axo pid,tty,user,command | perl -nle"m#^\s*(\d+).*(?:$args)# && !m#.dotfiles/bin/pid# && print \$1")
-fi
+
+	if [ ! "$1" ]; then
+		ps axo pid,tty,user,command
+	else
+		args="$1"
+		shift 
+		for arg in "$@";
+		do 
+			args="${args}|${arg}"; 
+		done
+		echo $(ps axo pid,tty,user,command | perl -nle"m#^\s*(\d+).*(?:$args)# && !m#.dotfiles/bin/pid# && print \$1")
+	fi
+}
+
+_pid "$@"
diff --git a/bin/server b/bin/server
--- a/bin/server
+++ b/bin/server
@@ -18,11 +18,40 @@
 #   `create-server [php | [py|python]]`
 #
 
-# Start an HTTP server from a directory, optionally specifying the port
-create-server() {
-	if [[ $1 == 'py' ]] || [[ $1 == 'python' ]]; then
+_create-server() {
+	local usage="$(basename $0): usage: $(basename $0) [-h|--help] [$(tput smul)php | [py|python]$(tput rmul)]"
+	local opt port ip
+	local type="$1"
+
+	# Test for known flags
+	for opt in $@
+	do
+		case $opt in
+			-h|--help)
+				printf "%s\n" "${usage}"
+				exit
+				;;
+			# test for an invalid flag, exit if not a valid flag
+			-*|--*)
+				printf "%s: usage: %s: invalid option\n%s\n" "$(basename "$0")" "$opt" "${usage}"
+				exit 1
+				;;
+		esac
+	done
+
+	if [[ ! "${type}" ]]; then 
+		printf "bash: %s: No type specified\n" "$(basename "$0")"
+		exit 1; 
+	fi
+
+	if [[ "${type}" != 'php' ]] && [[ ${type} != 'py' || ${type} != 'python' ]] && [[ ${type} != 'jekyll' ]]; then
+		printf "%s: %s: Not a valid server type\n" "$(basename "$0")" "${type}"
+		exit 1; 
+	fi
+
+	if [[ ${type} == 'py' ]] || [[ ${type} == 'python' ]]; then
 		# Get port (if specified)
-		local port="${1:-8000}"
+		port="8000"
 
 		# Open in the browser
 		open "http://localhost:${port}/"
@@ -37,11 +66,22 @@ create-server() {
 		python -c $'import SimpleHTTPServer;\nSimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map[""] = "text/plain";\nSimpleHTTPServer.test();' "$port"
 	fi
 
-	if [[ $1 == 'php' ]]; then
+	if [[ ${type} == 'php' ]]; then
 		# Start a PHP server from a directory, optionally specifying the port
-		local port="${1:-4000}"
-		local ip=$(ipconfig getifaddr en1)
+		port="4000"
+		ip=$(ipconfig getifaddr en0)
 		sleep 1 && open "http://${ip}:${port}/" &
 		php -S "${ip}:${port}"
 	fi
+
+	if [[ ${type} == 'jekyll' ]]; then
+		if ! type -P 'bundle' &> /dev/null; then
+			printf "%s⊘ Error:%s jekyll is required to run %s\n" "$(tput setaf 1)" "$(tput sgr0)" "$(basename $0)"
+			printf "Aborting!\n"
+		else
+			bundle exec jekyll serve --watch
+		fi
+	fi
 }
+
+_create-server "$@"
