Update library to reflect styleguide
- Major upgrade and rewrite of all scripts
- Update all scripts to use function, local variables and call function
  within
- Update all scripts that require a usage guide to set as local variable
- Update all scripts with dependency check
- Update all scripts with help and invalid option test flags
- Delete all scripts that are OS X dependent and Git dependent, as
  they'll be moved to a separate repository
- Create man pages for any necessary script
- Create more functions, `fs`, `get-cert-names`, `json`, `rgb-to-xterm`,
  `targz`, `update-ctags`.

Issue: #5

diff --git a/bin/compare-gzip b/bin/compare-gzip
--- a/bin/compare-gzip
+++ b/bin/compare-gzip
@@ -13,14 +13,43 @@
 #   @param   file    required
 #
 # Usage:
-#   `compare-zip filename.txt`
+#   `compare-gzip filename.txt`
 
-# (wc -c) count the bytes of passed in file, pass to stdout
-orig=$(wc -c < "$1")
-# (gzip -c) pass gzipped file to stdout, pipe output to byte count
-gzip=$(gzip -c "$1" | wc -c)
-# evaluate the expression
-ratio=$(expr $gzip \* 100 / $orig)
+_compare-gzip() {
+	local usage="$(basename $0): usage: $(basename $0) [-h|--help] $(tput smul)file$(tput rmul)"
+	local opt
+	local file="$1"
 
-printf "orig: %d bytes\n" "${orig}"
-printf "gzip: %d bytes (%2.2f%%)\n" "${gzip}" "${ratio}"
+	# Test for known flags
+	for opt in $@
+	do
+		case $opt in
+			-h|--help)
+				printf "%s\n" "${usage}"
+				exit
+				;;
+			# test for an invalid flag, exit if not a valid flag
+			-*|--*)
+				printf "%s: usage: %s: invalid option\n%s\n" "$(basename "$0")" "$opt"
+				exit 1
+				;;
+		esac
+	done
+
+	if [[ ! "${file}" ]]; then 
+		printf "bash: %s: No such file\n" "$(basename "$0")"
+		exit 1; 
+	fi
+
+	# (wc -c) count the bytes of passed in file, pass to stdout
+	local orig=$(wc -c < "$1")
+	# (gzip -c) pass gzipped file to stdout, pipe output to byte count
+	local gzip=$(gzip -c "$1" | wc -c)
+	# evaluate the expression
+	local ratio=$(expr $gzip \* 100 / $orig)
+
+	printf "orig: %d bytes\n" "${orig}"
+	printf "gzip: %d bytes (%2.2f%%)\n" "${gzip}" "${ratio}"
+}
+
+_compare-gzip "$@"
diff --git a/bin/eachdir b/bin/eachdir
--- a/bin/eachdir
+++ b/bin/eachdir
@@ -6,47 +6,33 @@
 # Description:
 #   Run one or more commands in one or more directories
 #
-# Dependencies:
-#   None
-#
-# Configuration:
-#   @param   dir[s]  required
-#
 # Usage:
-#   `compare-zip filename.txt`
+#   `eachdir pwd`
 
-function _eachdir() {
+_eachdir() {
+	local usage="$(basename $0): usage: $(basename $0) [$(tput smul)dirs --$(tput rmul)] commands"
+	local opt
+	local directory="$1"
 
-	if [[ "$1" == "-h" || "$1" == "--help" ]]; then cat <<HELP
-	Usage: eachdir [dirs --] commands
+	# Test for known flags
+	for opt in $@
+	do
+		case $opt in
+			-h|--help)
+				printf "%s\n" "${usage}"
+				exit
+				;;
+			# test for an invalid flag, exit if not a valid flag
+			-*|--*)
+				printf "%s: usage: %s: invalid option\n%s\n" "$(basename "$0")" "$opt" "${usage}"
+				exit 1
+				;;
+		esac
+	done
 
-	Run one or more commands in one or more dirs.
-
-	By default, all subdirs of the current dir will be iterated over, but if --
-	is specified as an arg, the dirs list will be made up of all args specified
-	before it. All remaining args are the command(s) to be executed for each dir.
-
-	Multiple commands must be specified as a single string argument.
-
-	In bash, aliasing like this allows you to specify aliases/functions:
-		alias eachdir=". eachdir"
-
-	Both of these print the working directory of every subdir of the current dir:
-		eachdir pwd
-		eachdir * -- pwd
-
-	Perform a "git pull" inside all subdirs starting with repo-:
-		eachdir repo-* -- git pull
-
-	Perform a few git-related commands inside all subdirs starting with repo-:
-		eachdir repo-* -- 'git fetch && git merge'
-HELP
-		return; 
-	fi
-
-	if [ ! "$1" ]; then
-	  echo 'You must specify one or more commands to run.'
-	  return 1
+	if [[ ! "${directory}" ]]; then 
+		printf "bash: %s: No command specified\n" "$(basename "$0")"
+		exit 1; 
 	fi
 
 	# For underlining headers.
@@ -57,12 +43,12 @@ HELP
 	local dashes d
 	local dirs=()
 	for d in "$@"; do
-	  if [[ "$d" == "--" ]]; then
-		dashes=1
-		shift $(( ${#dirs[@]} + 1 ))
-		break
-	  fi
-	  dirs=("${dirs[@]}" "$d")
+		if [[ "$d" == "--" ]]; then
+			dashes=1
+			shift $(( ${#dirs[@]} + 1 ))
+			break
+		fi
+		dirs=("${dirs[@]}" "$d")
 	done
 
 	# If -- wasn't specified, default to all subdirs of the current dir.
@@ -71,27 +57,26 @@ HELP
 	local nops=()
 	# Do stuff for each specified dir, in each dir. Non-dirs are ignored.
 	for d in "${dirs[@]}"; do
-	  # Skip non-dirs.
-	  [[ ! -d "$d" ]] && continue
-	  # If the dir isn't /, strip the trailing /.
-	  [[ "$d" != "/" ]] && d="${d%/}"
-	  # Execute the command, grabbing all stdout and stderr.
-	  output="$( (cd "$d"; eval "$@") 2>&1 )"
-	  if [[ "$output" ]]; then
-		# If the command had output, display a header and that output.
-		echo -e "${h1}${d}${h2}\n$output\n"
-	  else
-		# Otherwise push it onto an array for later display.
-		nops=("${nops[@]}" "$d")
-	  fi
+		# Skip non-dirs.
+		[[ ! -d "$d" ]] && continue
+		# If the dir isn't /, strip the trailing /.
+		[[ "$d" != "/" ]] && d="${d%/}"
+		# Execute the command, grabbing all stdout and stderr.
+		output="$( (cd "$d"; eval "$@") 2>&1 )"
+		if [[ "$output" ]]; then
+			# If the command had output, display a header and that output.
+			echo -e "${h1}${d}${h2}\n$output\n"
+		else
+			# Otherwise push it onto an array for later display.
+			nops=("${nops[@]}" "$d")
+		fi
 	done
 
 	# List any dirs that had no output.
 	if [[ ${#nops[@]} > 0 ]]; then
-	  echo "${h1}no output from${h2}"
-	  for d in "${nops[@]}"; do echo "$d"; done
+		echo "${h1}no output from${h2}"
+		for d in "${nops[@]}"; do echo "$d"; done
 	fi
-
 }
 
 # By putting the above code inside a function, if this file is sourced (which
diff --git a/bin/extract b/bin/extract
--- a/bin/extract
+++ b/bin/extract
@@ -1,6 +1,5 @@
 #!/usr/bin/env bash
 #
-#
 # Author:
 #   Brett Terpstra (@ttscoff)
 #   https://github.com/ttscoff/dotfiles/blob/master/.bash_profile
@@ -8,14 +7,30 @@
 # Description:
 #   Unarchive various compression formats based on extension
 #
-# Dependencies:
-#   None
-#
 # Usage:
 #   `extract foo.tar.bz2`
-usage="$(basename $0): usage: $(basename $0) <$(tput smul)file$(tput rmul)>"
 
-extract () { 
+
+_extract() { 
+	local usage="$(basename $0): usage: $(basename $0) [-h|--help] $(tput smul)file$(tput rmul)"
+	local opt
+
+	# Test for known flags
+	for opt in $@
+	do
+		case $opt in
+			-h|--help)
+				printf "%s\n" "${usage}"
+				exit
+				;;
+			# test for an invalid flag, exit if not a valid flag
+			-*|--*)
+				printf "%s: usage: %s: invalid option\n%s\n" "$(basename "$0")" "$opt" "${usage}"
+				exit 1
+				;;
+		esac
+	done
+
 	if test -f $1 &>/dev/null; then
 		case $1 in
 			*.tar.bz2)  tar xjf $1        ;;
@@ -30,12 +45,14 @@ extract () {
 			*.Z)        uncompress $1     ;;
 			*.dmg)      hdiutil mount $1  ;;
 			*)
-				printf 'bash: %s: %s: cannot be extracted via extract()\n' "$(basename "$0")" "$1"
+				printf 'bash: %s: %s: cannot be extracted\n' "$(basename "$0")" "$1"
 				exit 1
 				;;
 		esac
 	else
-		printf 'bash: %s: %s: is not a valid file\n' "$(basename "$0")" "$1"
+		printf 'bash: %s: %s: No such file\n' "$(basename "$0")" "$1"
 		exit 1
 	fi
 }
+
+_extract "$@"
diff --git a/bin/find-todos b/bin/find-todos
--- a/bin/find-todos
+++ b/bin/find-todos
@@ -20,53 +20,64 @@
 #   `find-todos ~/Desktop // Searches ~/Desktop, outputs to todo.md in cwd
 #   `find-todos // searches cwd, outputs to todo.md in cwd
 
-# @TODO: turn any todo into an issue on Github
-usage="$(basename $0): usage: $(basename $0) [-o|--output $(tput smul)file$(tput rmul)] [dir|file]"
+_find-todos() {
+	if ! type -P 'git' &> /dev/null; then
+		printf "%s⊘ Error:%s Git is required to run %s\n" "$(tput setaf 1)" "$(tput sgr0)" "$(basename $0)"
+		printf "Aborting!\n"
+		exit
+	fi
 
-# Test for known flags
-for opt in "$@"
-do
-	case "$opt" in
-		-o | --output)
-			output=$2
-			shift 2
-			;;
-		-*)
-			printf 'bash: %s: %s: invalid option\n%s\n' "$(basename "$0")" "$1" "${usage}"
-			exit 2
-			;;
-		*)  # No more options
-			break
-			;;
-	esac
-done
+	# @TODO: turn any todo into an issue on Github
+	local usage="$(basename $0): usage: $(basename $0) [-h|--help] [-o|--output $(tput smul)file$(tput smul)] [dir|file]"
+	local opt output directory github_url
 
-if [[ "$1" == "-o" ]] || [[ "$2" == "-o" ]]; then
-	printf 'bash: %s: %s: invalid option\n%s\n' "$(basename "$0")" "$1" "${usage}"
-	exit 2
-fi
+	# Test for known flags
+	for opt in "$@"
+	do
+		case "$opt" in
+			-o | --output)
+				output=$2
+				shift 2
+				;;
+			-*)
+				printf 'bash: %s: %s: invalid option\n%s\n' "$(basename "$0")" "$1" "${usage}"
+				exit 2
+				;;
+			*)  # No more options
+				break
+				;;
+		esac
+	done
 
-if [[ -f "$1" || -d "$1" ]]; then
-	directory=$1
-else
-	directory="${PWD}"
-fi
+	if [[ "$1" == "-o" ]] || [[ "$2" == "-o" ]]; then
+		printf 'bash: %s: %s: invalid option\n%s\n' "$(basename "$0")" "$1" "${usage}"
+		exit 2
+	fi
 
-if [[ ! -z "${output}" ]]; then
-	output="${directory}/${output}"
-else
-	output="${directory}/TODO.md"
-fi
+	if [[ -f "$1" || -d "$1" ]]; then
+		directory=$1
+	else
+		directory="${PWD}"
+	fi
 
-if ! grep -nr "@TODO:" ${directory} &>/dev/null; then
-	printf 'No results found\n'
-	exit 1
-else
-	rm -rf "${output}"
-	echo "# TODO" > "${output}"
-	echo >> "${output}"
-	# grep -v grep excludes this line from being included (http://superuser.com/a/409658)
-	github_url="$(git remote show -n origin | grep 'Fetch URL' | awk -F: '{print $2 ":" substr($3, 0, length($3)-4) }')"
-	grep -nr "@TODO:" ${directory} | grep -v grep | awk -F: 'path=split($1,arr,"/") ( length($4) > 0 ) {print "- [ ] ["arr[length(arr) - 1]"/"arr[length(arr)]":"$2"]("url"/blob/master/"arr[length(arr) - 1]"/"arr[length(arr)]"#L"$2") - "substr($4,2)}' url="$github_url" >> "${output}"
-	printf "TODOs can be found in ${output}\n"
-fi
+	if [[ ! -z "${output}" ]]; then
+		output="${directory}/${output}"
+	else
+		output="${directory}/TODO.md"
+	fi
+
+	if ! grep -nr "@TODO:" ${directory} &>/dev/null; then
+		printf 'No results found\n'
+		exit 1
+	else
+		rm -rf "${output}"
+		echo "# TODO" > "${output}"
+		echo >> "${output}"
+		# grep -v grep excludes this line from being included (http://superuser.com/a/409658)
+		github_url="$(git remote show -n origin | grep 'Fetch URL' | awk -F: '{print $2 ":" substr($3, 0, length($3)-4) }')"
+		grep -nr "@TODO:" ${directory} | grep -v grep | awk -F: 'path=split($1,arr,"/") ( length($4) > 0 ) {print "- [ ] ["arr[length(arr) - 1]"/"arr[length(arr)]":"$2"]("url"/blob/master/"arr[length(arr) - 1]"/"arr[length(arr)]"#L"$2") - "substr($4,2)}' url="$github_url" >> "${output}"
+		printf "TODOs can be found in ${output}\n"
+	fi
+}
+
+_find-todos "$@"
diff --git a/bin/fpo b/bin/fpo
--- a/bin/fpo
+++ b/bin/fpo
@@ -17,83 +17,105 @@
 #   `fpo 300x169 fpo/images // 1 300x169 pixel random image downloaded to fpo/images
 #   `fpo 300x169 // 1 300x169 pixel random images downloaded to cwd
 
-# allowable categories
-# categories=(abstract animals business cats city food nightlife fashion people nature sports technics transport)
-# regex to test for number
-re='^[0-9]+$'
+_fpo() {
+	local usage="$(basename $0): usage: $(basename $0) [-h|--help] [amount] dimensions [category] ["$(tput smul)"dir"$(tput rmul)"]"
 
-# if the first positional parameter is not a number, its the dimension
-# set the amount to 1 and dimensions to what was passed in
-# remove the dimensions from the positional parameters
-# if not, set amount and dimensions to what was passed in
-# remove both positional parameters
-if ! [[ $1 =~ $re ]]; then
-	amount=1
-	dimensions=$1
-	shift 1
-else
-	amount=$1
-	dimensions=$2
-	shift 2
-fi
-
-# split dimensions argument by letter 'x'
-#dimensions=(${dimensions//x/ })
-
-# check if dimensions is empty, if it is error and exit
-# this is there to ensure that the dimensions is passed in at the very leaset
-if [[ -z ${dimensions} ]]; then
-	printf "%s: %s: Width and height must be supplied" "$(basename $0)" "${dimensions}"
-	exit 1
-fi
-
-# if the next parameter passed in is not a directory
-# then its the format and directory is the next one
-# remove the format positional parameter
-# if it is a directory then assume default format of 'png'
-if [[ ! -d $1 ]]; then
-	format=$1
-	directory=$2
-	shift 1
-else
-	format="png"
-	directory=$1
-fi
-
-api_url="http://hhhhold.com/"
-
-# http://stackoverflow.com/questions/238073/how-to-add-a-progress-bar-to-a-shell-script
-# start progress bar
-while :;do echo -n .;sleep 1;done &
-
-# check response header from github user passed in
-# http://stackoverflow.com/a/10724976/1536779
-response="$(curl --write-out %{http_code} --silent --output /dev/null "${api_url}")"
-
-# kill the progress bar
-kill $!; trap 'kill $!' SIGTERM
-
-# if reponse is greater than or equal to 400 somethings wrong
-if [[ "${response}" -ge 400 ]]; then
-	printf '%s: %s is unavailable. Try again later\n' "$(basename "$0")" "$api_url"
-	#debug statement
-	#printf 'Github HTTP Response code: %s\n' "${response}"
-	exit 3
-fi
-
-URL="${api_url}/${dimensions}/${format}"
-
-#check if only 1 requested, no loop
-if [[ $amount -gt 1 ]]; then
-	counter=1
-	#random=$(shuf -i 1-10 -n 1)
-	while [ $counter -lt $amount ]
+	# Test for known flags
+	for opt in $@
 	do
-		#wget ${URL} -O ${dimensions}_${counter}.${format} -P ${directory}
-		curl -#fLo "${directory}/${dimensions}_${counter}.${format}" "${URL}"
-		let counter=counter+1
+		case $opt in
+			-h|--help)
+				printf "%s\n" "${usage}"
+				exit
+				;;
+			# test for an invalid flag, exit if not a valid flag
+			-*|--*)
+				printf "%s: usage: %s: invalid option\n%s\n" "$(basename "$0")" "$opt" "${usage}"
+				exit 1
+				;;
+		esac
 	done
-else
-	#wget ${URL} -O ${dimensions}_$(shuf -i 1-10 -n 1).${format} -P ${directory}
-	curl -#fLo "${directory}/${dimensions}_$(shuf -i 1-10 -n 1).${format}" "${URL}"
-fi
+
+	# allowable categories
+	# categories=(abstract animals business cats city food nightlife fashion people nature sports technics transport)
+	# regex to test for number
+	local re='^[0-9]+$'
+	local amount dimensions format response URL counter
+	local api_url="http://hhhhold.com/"
+
+	# if the first positional parameter is not a number, its the dimension
+	# set the amount to 1 and dimensions to what was passed in
+	# remove the dimensions from the positional parameters
+	# if not, set amount and dimensions to what was passed in
+	# remove both positional parameters
+	if ! [[ $1 =~ $re ]]; then
+		amount=1
+		dimensions=$1
+		shift 1
+	else
+		amount=$1
+		dimensions=$2
+		shift 2
+	fi
+
+	# split dimensions argument by letter 'x'
+	#dimensions=(${dimensions//x/ })
+
+	# check if dimensions is empty, if it is error and exit
+	# this is there to ensure that the dimensions is passed in at the very leaset
+	if [[ -z ${dimensions} ]]; then
+		printf "bash: %s: Width and height must be supplied" "$(basename $0)"
+		exit 1
+	fi
+
+	# if the next parameter passed in is not a directory
+	# then its the format and directory is the next one
+	# remove the format positional parameter
+	# if it is a directory then assume default format of 'png'
+	if [[ ! -d $1 ]]; then
+		format=$1
+		directory=$2
+		shift 1
+	else
+		format="png"
+		directory=$1
+	fi
+
+	# http://stackoverflow.com/questions/238073/how-to-add-a-progress-bar-to-a-shell-script
+	# start progress bar
+	while :;do echo -n .;sleep 1;done &
+
+	# check response header from github user passed in
+	# http://stackoverflow.com/a/10724976/1536779
+	response="$(curl --write-out %{http_code} --silent --output /dev/null "${api_url}")"
+
+	# kill the progress bar
+	kill $!; trap 'kill $!' SIGTERM
+
+	# if reponse is greater than or equal to 400 somethings wrong
+	if [[ "${response}" -ge 400 ]]; then
+		printf 'bash: %s: %s is unavailable. Try again later\n' "$(basename "$0")" "$api_url"
+		#debug statement
+		#printf 'Github HTTP Response code: %s\n' "${response}"
+		exit 3
+	fi
+
+	URL="${api_url}/${dimensions}/${format}"
+
+	#check if only 1 requested, no loop
+	if [[ $amount -gt 1 ]]; then
+		counter=1
+		#random=$(shuf -i 1-10 -n 1)
+		while [ $counter -lt $amount ]
+		do
+			#wget ${URL} -O ${dimensions}_${counter}.${format} -P ${directory}
+			curl -#fLo "${directory}/${dimensions}_${counter}.${format}" "${URL}"
+			let counter=counter+1
+		done
+	else
+		#wget ${URL} -O ${dimensions}_$(shuf -i 1-10 -n 1).${format} -P ${directory}
+		curl -#fLo "${directory}/${dimensions}_$(shuf -i 1-10 -n 1).${format}" "${URL}"
+	fi
+}
+
+_fpo "$@"
